#!/bin/bash

# Arithmetic Functions

num1=10
num2=5

# Addition
sum=$((num1 + num2))
echo "Sum: $sum"

# Subtraction
difference=$((num1 - num2))
echo "Difference: $difference"

# Multiplication
product=$((num1 * num2))
echo "Product: $product"

# Division
quotient=$((num1 / num2))
echo "Quotient: $quotient"

# Modulus
remainder=$((num1 % num2))
echo "Remainder: $remainder"

# Exponentiation
exponentiation=$((num1 ** num2))
echo "Exponentiation: $exponentiation"
